#Refazer o arquivo
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoNode
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass
    volumes:
      - mysqlvol1234:/var/lib/mysql
    networks:
      - todoNet

  todonode:
    image: todonode
    ports:
      - 3000:3000

volumes:
  mysqlvol1234:

networks:
  todoNet:
    driver: bridge